name: Generate pacman animation

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # permite execução manual
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write # Permissão para escrever no repositório
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Passo 1: Gera a animação do Pac-Man no tema CLARO (padrão)
      - name: Generate light pacman SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: kendylopes
          # Nenhum tema especificado, então usa o padrão 'light'
          # O ficheiro será 'pacman-contribution-graph.svg' por padrão

      # Passo 2: Gera a animação do Pac-Man no tema ESCURO
      - name: Generate dark pacman SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: kendylopes
          theme_name: 'dark' # Define o tema como escuro
          file_name: 'pacman-contribution-graph-dark.svg' # Define um nome de ficheiro diferente

      # Passo 3: Envia AMBOS os ficheiros gerados para a branch 'output'
      - name: Push SVGs to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist # A pasta onde ambos os SVGs são guardados
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
